#include "MainWindow.h"
#include "ui_MainWindow.h" // Generated by uic using the form created with QtDesigner

MainWindow::MainWindow(QWidget* parent)
	: QMainWindow(parent)
	, ui(new Ui::MainWindow)
{
	// Apply the design made with QtDesigner to this QMainWindow
	ui->setupUi(this);

	// Set up the interface
	setupConnections();
}

MainWindow::~MainWindow()
{
	delete ui;
}

void MainWindow::setupConnections()
{
	// QtDesigner knows QMainWindow classes but, it does not know this inherited MainWindow
	// class, therefore, it ignores MainWindow's slots. Connections must be done manually
	connect(ui->actionNew, SIGNAL(triggered()), this, SLOT(actionNewTriggered()));
}

#include <QDebug>

void MainWindow::actionNewTriggered()
{
	qDebug() << "action new was triggered!";
}
